coverage:
  status:
    project:
      default:
        target: 100%
        threshold: 1%
        flags: 
          - unit
        paths: 
          - "src"
       # advanced settings
        branches: 
          - main
        if_ci_failed: error
        informational: false
        only_pulls: false