# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

permissions:
  contents: read

concurrency:
  group: ${{ github.event.number || github.run_id }}
  cancel-in-progress: true

jobs:
  pr_test:
    if: github.refs != 'refs/heads/main' && github.refs != 'refs/heads/master'
    env:
      PYTHONDEVMODE: 1
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        os: [ubuntu-latest, macos-latest, windows-latest]
        install-via: [pip]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.arch }}
        allow-prereleases: false

    - name: Set Variables
      id: set_variables
      shell: bash
      run: |
        echo "PY=$(python -c 'import hashlib, sys;print(hashlib.sha256(sys.version.encode()+sys.executable.encode()).hexdigest())')" >> $GITHUB_OUTPUT
        echo "PIP_CACHE=$(pip cache dir)" >> $GITHUB_OUTPUT

    - name: Cache pip
      uses: actions/cache@v4
      with:
        path: ${{ steps.set_variables.outputs.PIP_CACHE }}
        key: ${{ runner.os }}-pip-${{ steps.set_variables.outputs.PY }}

    - name: Cache venv
      uses: actions/cache@v4
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ matrix.arch }}-${{ matrix.python-version }}-${{ hashFiles('pdm.lock') }}
        restore-keys: |
          venv-${{ runner.os }}-${{ matrix.arch }}-${{ matrix.python-version }}-

    - name: Install current PDM via pip
      if: matrix.install-via == 'pip'
      run: |
        python -m pip install pdm
        pdm info -v
        pdm venv list -v
        pdm use -f .venv
        echo "$VIRTUAL_ENV/bin" >> $GITHUB_PATH
        echo "VIRTUAL_ENV=$VIRTUAL_ENV" >> $GITHUB_ENV
        echo "GITHUB_PATH=$GITHUB_PATH"
        echo "GITHUB_ENV=$GITHUB_ENV"

    - name: Lint + Run unit & acceptance tests + Measure code coverage
      run: |
        pdm use -f .venv
        pdm install -v -dGlint --no-self --no-isolation
        pdm run -v lint
        pdm install -v -dGtest --no-self --no-isolation
        pdm run -v pytest
        pdm run -v doctests

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: sr-murthy/continuedfractions
        file: ./coverage.xml
        flags: unit

  main_update:
    if: github.refs == 'refs/heads/main' || github.refs == 'refs/heads/master'
    env:
      PYTHONDEVMODE: 1
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        os: [ubuntu-latest, macos-latest, windows-latest]
        install-via: [pip]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.arch }}
        allow-prereleases: false

    - name: Set Variables
      id: set_variables
      shell: bash
      run: |
        echo "PY=$(python -c 'import hashlib, sys;print(hashlib.sha256(sys.version.encode()+sys.executable.encode()).hexdigest())')" >> $GITHUB_OUTPUT
        echo "PIP_CACHE=$(pip cache dir)" >> $GITHUB_OUTPUT

    - name: Cache pip
      uses: actions/cache@v4
      with:
        path: ${{ steps.set_variables.outputs.PIP_CACHE }}
        key: ${{ runner.os }}-pip-${{ steps.set_variables.outputs.PY }}

    - name: Cache venv
      uses: actions/cache@v4
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ matrix.arch }}-${{ matrix.python-version }}-${{ hashFiles('pdm.lock') }}
        restore-keys: |
          venv-${{ runner.os }}-${{ matrix.arch }}-${{ matrix.python-version }}-

    - name: Install current PDM via pip
      if: matrix.install-via == 'pip'
      run: |
        python -m pip install pdm
        pdm info -v
        pdm venv list -v
        pdm use -f .venv
        echo "$VIRTUAL_ENV/bin" >> $GITHUB_PATH
        echo "VIRTUAL_ENV=$VIRTUAL_ENV" >> $GITHUB_ENV
        echo "GITHUB_PATH=$GITHUB_PATH"
        echo "GITHUB_ENV=$GITHUB_ENV"

    - name: Run acceptance tests
      run: |
        pdm use -f .venv
        pdm run -v doctests
